services:
  - type: web
    name: student-assessment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - "**/*.html"
        - "**/*.css"
        - "**/*.js"
        - "**/*.json"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
