services:
  - type: web
    name: student-assessment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app -c gunicorn_config.py
    healthCheckPath: /
    plan: starter
    autoDeploy: true
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - "**/*.html"
        - "**/*.css"
        - "**/*.js"
        - "**/*.json"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: RENDER
        value: true
      - key: LLM_MODEL_PREFERENCE
        value: llama3
